//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funcky.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Funcky.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerable.Empty&lt;Type&gt;() returns an empty Enumerable.
        /// </summary>
        internal static string EnumerableRepeatNeverAnalyzerDescription {
            get {
                return ResourceManager.GetString("EnumerableRepeatNeverAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Enumerable.Empty&lt;{1}&gt;() instead of Enumerable.Repeat({0}, 0).
        /// </summary>
        internal static string EnumerableRepeatNeverAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EnumerableRepeatNeverAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Enumerable.Repeat with no element.
        /// </summary>
        internal static string EnumerableRepeatNeverAnalyzerTitle {
            get {
                return ResourceManager.GetString("EnumerableRepeatNeverAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcky provides Sequence.Return to create an IEnumerable of a single item.
        /// </summary>
        internal static string EnumerableRepeatOnceAnalyzerDescription {
            get {
                return ResourceManager.GetString("EnumerableRepeatOnceAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Sequnce.Return({0}) instead of Enumerable.Repeat({0}, 1) .
        /// </summary>
        internal static string EnumerableRepeatOnceAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EnumerableRepeatOnceAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Enumerable.Repeat for a single element.
        /// </summary>
        internal static string EnumerableRepeatOnceAnalyzerTitle {
            get {
                return ResourceManager.GetString("EnumerableRepeatOnceAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this method with argument names.
        /// </summary>
        internal static string UseArgumentNamesAnalyzerDescription {
            get {
                return ResourceManager.GetString("UseArgumentNamesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add argument name for argument &apos;{0}&apos;.
        /// </summary>
        internal static string UseArgumentNamesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UseArgumentNamesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this method with argument names.
        /// </summary>
        internal static string UseArgumentNamesAnalyzerTitle {
            get {
                return ResourceManager.GetString("UseArgumentNamesAnalyzerTitle", resourceCulture);
            }
        }
    }
}
