//HintName: ParseExtensions.g.cs
// <auto-generated/>
#nullable enable

using Funcky.Internal;

namespace Funcky.Extensions
{
    public static partial class ParseExtensions
    {
        [Pure]
        public static partial Option<TEnum> ParseEnumOrNone<TEnum>(this string candidate)
            where TEnum : struct => FailToOption<TEnum>.FromTryPattern(Enum.TryParse, candidate);
    }
}