//HintName: .g.cs
// <auto-generated/>
#nullable enable

namespace Funcky.Extensions
{
    public static partial class ParseExtensions
    {
        [global::System.Diagnostics.Contracts.Pure]
        public static Funcky.Monads.Option<global::Funcky.Extensions.Target> ParseTargetOrNone(this string candidate, bool caseSensitive, global::System.IFormatProvider provider) => global::Funcky.Extensions.Target.TryParse(candidate, caseSensitive, provider, out var result) ? result : default(Funcky.Monads.Option<global::Funcky.Extensions.Target>);
    }
}