//HintName: ParseExtensions.g.cs
// <auto-generated/>
#nullable enable

using System.Diagnostics.Contracts;
using Funcky.Internal;
using Funcky.Monads;

namespace Funcky.Extensions
{
    public static partial class ParseExtensions
    {
        public static partial Option<DateTime> ParseDateTimeOrNone(this string candidate, IFormatProvider provider, DateTimeStyles styles) => DateTime.TryParse(candidate, provider, styles, out var result) ? result : Option<DateTime>.None;
    }
}