//HintName: .g.cs
// <auto-generated/>
#nullable enable

namespace Funcky.Extensions
{
    public static partial class ParseExtensions
    {
        [global::System.Diagnostics.Contracts.Pure]
        public static Funcky.Monads.Option<bool> ParseBooleanOrNone(this string? candidate) => bool.TryParse(candidate, out var result) ? result : default(Funcky.Monads.Option<bool>);
        [global::System.Diagnostics.Contracts.Pure]
        public static Funcky.Monads.Option<bool> ParseBooleanOrNone(this global::System.ReadOnlySpan<char> candidate) => bool.TryParse(candidate, out var result) ? result : default(Funcky.Monads.Option<bool>);
    }
}
