//HintName: .g.cs
// <auto-generated/>
#nullable enable

namespace Funcky.Extensions
{
    public static partial class ParseExtensions
    {
        [global::System.Diagnostics.Contracts.Pure]
        public static Funcky.Monads.Option<global::Funcky.Extensions.Target> ParseTargetOrNone(this string candidate, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("foo")] string format) => global::Funcky.Extensions.Target.TryParse(candidate, format, out var result) ? result : default(Funcky.Monads.Option<global::Funcky.Extensions.Target>);
    }
}